name: my_university_isuct
description: Все для студентов
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.2.3+2

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  grouped_list: ^5.1.2
  table_calendar: ^3.0.9
  # isoweek: ^1.1.4
  flutter_staggered_grid_view: ^0.7.0
  auto_size_text: ^3.0.0
  path: ^1.8.3
  get: ^4.6.6
  sqflite: ^2.3.0
  html: ^0.15.4
  convert: ^3.1.1
  home_widget: ^0.3.0
  workmanager: ^0.5.1
  dio: ^5.3.3
  flutter_modular: ^6.3.2
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  path_provider: ^2.1.1
  path_provider_android: ^2.2.0
  rxdart: ^0.27.7
  flutter_downloader: ^1.11.2
  flutter_inappwebview: ^5.7.2+3
  permission_handler: ^11.0.0
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  flutter_quill: 7.4.6
  icons_plus: any
  appmetrica_plugin: any
  package_info_plus: any
  intro_slider: any
  flutter_native_splash: ^2.3.2
  flutter_rustore_update: ^0.0.3
  auto_start_flutter: ^0.1.1
  app_settings: ^5.1.1


  hive: any
  provider: any
  cupertino_icons: ^1.0.2
  vsc_quill_delta_to_html: ^1.0.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  image_path: "assets/logo/icon-original.png"
  image_path_android: "assets/logo/icon-original.png"
  # image_path_ios: "assets//icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: false # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#2962FF" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/logo/icon-foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_padding: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true


flutter_native_splash:
  color: "#2962FF"
  image: "assets/logo/icon-foreground.png"
  fullscreen: true
  android: true
  ios: true
  # android_12:
  #   color: "#2962FF"
  #   # branding: "assets/logo/icon-foreground.png"
  #   image: "assets/logo/icon-foreground.png"
    
 

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/logo/
    - .env

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
